/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASkeletonImage: typeof import('ant-design-vue/es')['SkeletonImage']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ConvertUnit: typeof import('./src/components/ConvertUnit.vue')['default']
    ImageMng: typeof import('./src/components/ImageMng.vue')['default']
  }
}
